### PR TITLE
Fix FP S2428 (`prefer-object-literal`): Ignore circular reference assignments

### LINKED ISSUE #391: Fix FP S2428 (`prefer-object-literal`): Ignore circular reference assignments
```js
const O = {}; // => error  Declare one or more properties of this object inside of the object literal syntax instead of using separate statements  sonarjs/prefer-object-literal
O.self = O;
```
The problem is that we can't define self references in the object literal. Sure, it can be worked around - but the error in this case is not what is expected from this rule.

### PR DESCRIPTION
**Pull request by yassin-kammoun-sonarsource**
Fixes #391

### CODE REVIEW

File: src/rules/prefer-object-literal.ts [hunk 1]
```diff
@@ -69,9 +69,8 @@ function checkObjectInitialization(
     const objectDeclaration = getObjectDeclaration(statements[index]);
     // eslint-disable-next-line sonarjs/no-collapsible-if
     if (objectDeclaration && isIdentifier(objectDeclaration.id)) {
-      if (
-        isPropertyAssignment(statements[index + 1], objectDeclaration.id, context.getSourceCode())
-      ) {
+      const stmt = statements[index + 1];
+      if (isPropertyAssignment(stmt, objectDeclaration.id, context.getSourceCode())) {
```
Comment (ilia-kebets-sonarsource) [inline src/rules/prefer-object-literal.ts:73]:
```suggestion
      const nextStmt = statements[index + 1];
      if (isPropertyAssignment(nextStmt, objectDeclaration.id, context.getSourceCode())) {
```

**Review by ilia-kebets-sonarsource — APPROVED** [review]
small suggestion, otherwise LGTM!
