### PR TITLE
Fix no-unused-collection: should not fire if collection is exported

### LINKED ISSUE #197: no-unused-collections should not fire if collection is exported
**I want to report a bug.**

Exported members of a module / class should be ignored.

**Reproducer**

```javascript

export collection = new Map()
```

### PR DESCRIPTION
**Pull request by yassin-kammoun-sonarsource**
Fixes #197

### CODE REVIEW

File: src/rules/no-unused-collection.ts [hunk 1]
```diff
@@ -61,7 +61,24 @@ function collectUnusedCollections(
...
+function isExported(variable: TSESLint.Scope.Variable) {
+  const definition = variable.defs[0];
+  if (definition) {
+    let { node }: { node: TSESTree.Node | undefined } = definition;
+    if (node.type === 'VariableDeclarator') {
+      node = node.parent;
+    } else if (definition.type === 'Parameter') {
+      return false;
+    }
+    return node?.parent?.type.indexOf('Export') === 0;
```
Comment (vilchik-elena) [inline src/rules/no-unused-collection.ts:73]: why not simply `startsWith` instead?

File: src/rules/no-unused-collection.ts [hunk 2]
```diff
@@ -61,7 +61,24 @@ function collectUnusedCollections(
   });
 }
 
+function isExported(variable: TSESLint.Scope.Variable) {
```
Comment (vilchik-elena) [inline src/rules/no-unused-collection.ts:64]: I don't see a lot of point in all this logic here. I suggest following:
```js
  const definition = variable.defs[0];
  return definition && definition.node.parent?.parent?.type.startsWith('Export');
```

**Review by vilchik-elena — CHANGES_REQUESTED** [review]

**Review by vilchik-elena — APPROVED** [review]
